### ISSUE TITLE
Terminal Reading

### ISSUE THREAD

**Issue by TrevorBrunette** [TrevorBrunette/EzASM#10]
**As a** program user
**I want** to be able to read information from the terminal
**So that** I can interact with the program user.

**Request Description**
Implement instructions to read characters to the terminal interpreted as a certain data type. These instructions must properly handle errors where an invalid input is provided e.g., a string provided for an integer.
`readi` (register)
`readf` (register)
`readc` (register)
`reads` (register with ptr) (size of string buffer)

**Comment by WyattRoss** [comment]
Meaningful use of these features by an end user is gated by #8 and #17

**Comment by TrevorBrunette** [comment]
Implemented in #57
